# Generated by Django 4.0.4 on 2022-05-16 20:42

from django.db import migrations, models
from pkg_resources import require


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('activities', models.TextField(max_length=500)),
                ('pet_friendly', models.BooleanField()),
            ],
        ),
    ]
