# Generated by Django 4.0.4 on 2022-05-19 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pet_friendly', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.camp')),
            ],
        ),
        migrations.AddField(
            model_name='camp',
            name='features',
            field=models.ManyToManyField(to='main_app.features'),
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(choices=[('N', 'National Park'), ('S', 'State Park'), ('P', 'Private'), ('B', 'Boondock')], default='N', max_length=1)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.camp')),
            ],
        ),
    ]
