# Generated by Django 4.0.4 on 2022-05-18 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(choices=[('N', 'National Park'), ('S', 'State Park'), ('P', 'Private'), ('B', 'Boondock')], default=0, max_length=1)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.camp')),
            ],
        ),
    ]
