# Generated by Django 4.0.4 on 2022-05-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.TextField(choices=[('21', 'Wildlife Viewing'), ('22', 'Hunting'), ('23', 'Swimming'), ('24', 'Fishing'), ('25', 'Hiking'), ('26', 'Biking'), ('27', 'Climbing'), ('28', 'Horse Riding'), ('29', 'ATV Trail'), ('30', 'Water Sports'), ('31', 'Boating'), ('32', 'Guided Nature Walks'), ('33', 'Backpacking'), ('34', 'Stargazing')], default=0, max_length=500)),
                ('amenities', models.CharField(choices=[('1', 'Privacy'), ('2', 'Fire Pit'), ('3', 'Picnic Table'), ('4', 'Flush Toilets'), ('5', 'Cell Sevice'), ('6', 'Accessible'), ('7', 'Dump Station'), ('8', 'Showers'), ('9', 'Food Locker'), ('10', 'Vault Toilet'), ('11', 'Picnic Areas')], default=0, max_length=100)),
                ('sites', models.CharField(choices=[('T', 'Tent'), ('C', 'Camper'), ('X', 'Cabin'), ('E', 'Electric'), ('NE', 'Non Electric')], default=0, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='camp',
            name='activities',
        ),
        migrations.AddField(
            model_name='camp',
            name='features',
            field=models.ManyToManyField(to='main_app.features'),
        ),
    ]
