# Generated by Django 4.0.4 on 2022-05-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_features_remove_camp_activities_camp_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='activities',
            field=models.CharField(choices=[('21', 'Wildlife Viewing'), ('22', 'Hunting'), ('23', 'Swimming'), ('24', 'Fishing'), ('25', 'Hiking'), ('26', 'Biking'), ('27', 'Climbing'), ('28', 'Horse Riding'), ('29', 'ATV Trail'), ('30', 'Water Sports'), ('31', 'Boating'), ('32', 'Guided Nature Walks'), ('33', 'Backpacking'), ('34', 'Stargazing')], default=0, max_length=100),
        ),
    ]
