# Generated by Django 4.0.4 on 2022-05-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_features_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='features',
            name='sites',
        ),
        migrations.AlterField(
            model_name='agency',
            name='organization',
            field=models.CharField(choices=[('N', 'National Park'), ('S', 'State Park'), ('P', 'Private'), ('B', 'Boondock')], default='N', max_length=1),
        ),
    ]
