# Generated by Django 4.0.4 on 2022-05-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_features_amenities_remove_features_sites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='activities',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.camp')),
            ],
        ),
    ]
